services:
  lark-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lark_web
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: production

networks:
  lark-network:
    external: true
